#  Time duration:
#    µs - microseconds
#    ms - milliseconds
#    s - seconds
#    m - minutes
#    h - hours

host                = '0.0.0.0'
port                = 3333
numThreads          = 2
statisticInterval   = '1m'

[influxdb]
server    = '127.0.0.1'
port      = 8089

[mysql]
charset   = 'utf8'
database  = 'thegame'
server    = '127.0.0.1'
user      = ''
password  = ''
port      = 0
maxIdleTime = 600

[room]
numThreads = 4
updateInterval = '50ms'
simulationsPerUpdate = 5
spawnPosTryCount = 10

checkPlayersInterval = '5s'
updateLeaderboardInterval = '1s'
destroyOutdatedCellsInterval = '3s'
checkMothersInterval = '10s'
produceMothersInterval = '1s'

viewportBase = 743
viewportBuffer = 0.1
aspectRatio = 1.77778

width = 6144
height = 6144
maxMass = 50000
maxPlayers = 50
maxRadius = 100
leaderboardVisibleItems = 20
scaleRatio = 0.75
explodeVelocity = 500

playerMaxCells = 16
playerDeflationInterval = '2m'
playerDeflationRatio = 0.10
playerAnnihilationInterval = '5m'
playerForceRatio = 2.5

botNames = ['Nebula', 'Solaris', 'Celestia', 'Quasar', 'Zenith', 'Lunar', 'Stardust', 'Nova', 'Galaxia', 'Cosmos']
botStartMass = 300
botForceCornerRatio = 25000.0
botForceFoodRatio = 3000.0
botForceHungerRatio = 10000.0
botForceDangerRatio = 50000.0
botForceStarRatio = 15000.0

resistanceRatio = 750.0
elasticityRatio = 30.0

cellMinMass = 35
cellRadiusRatio = 6.0

avatarStartMass = 250
avatarMinSpeed = 200
avatarMaxSpeed = 600
avatarExplodeMinMass = 35
avatarExplodeParts = 5
avatarSplitMinMass = 100
avatarSplitVelocity = 600
avatarEjectMinMass = 82
avatarEjectVelocity = 550
avatarEjectMass = 250
avatarEjectMassLoss = 47
avatarRecombineTime = 8

foodStartAmount = 2000
foodMaxAmount = 5000
foodMass = 5
foodRadius = 8
foodMinVelocity = 190
foodMaxVelocity = 210
foodResistanceRatio = 30.0

virusStartMass = 165
virusStartAmount = 10
virusMaxAmount = 20
virusLifeTime = '5m'
virusColor = 13

phageStartMass = 165
phageStartAmount = 10
phageMaxAmount = 20
phageLifeTime = '5m'
phageColor = 14

motherStartMass = 240
motherStartAmount = 10
motherMaxAmount = 20
motherLifeTime = '10m'
motherExplodeMass = 3000
motherColor = 12
motherCheckRadius = 60

[room.generator.food]
interval = '1s'
quantity = 3

[room.generator.virus]
interval = '7s'
quantity = 1

[room.generator.phage]
interval = '7s'
quantity = 1

[room.generator.mother]
interval = '10s'
quantity = 1
